### Load Dataset First

In [21]:

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
df = pd.read_csv("student_performance_100_rows_with_names.csv")

df 

,Student_ID,Student_Name,Math,Physics,Chemistry,English,Computer_Science,Average,Performance_Category
0,S001,Reyansh Agarwal,65,72,46,84,63,66.0,Below Average
1,S002,Myra Kapoor,42,85,49,54,80,62.0,Below Average
2,S003,Krishna Joshi,58,88,90,87,54,75.4,Above Average
3,S004,Sara Kapoor,59,42,38,88,84,62.2,Below Average
4,S005,Aanya Gupta,71,61,95,73,72,74.4,Above Average
...,...,...,...,...,...,...,...,...,...
95,S096,Ira Pandya,61,53,74,83,60,66.2,Below Average
96,S097,Aarav Nair,94,92,49,89,61,77.0,Above Average
97,S098,Sai Pandya,61,89,40,97,59,69.2,Below Average
98,S099,Aditya Agarwal,85,96,38,86,81,77.2,Above Average


In [22]:
subjects = ["Math", "Physics", "Chemistry", "English", "Computer_Science"]
data = df[subjects].values
print(data)

[[65 72 46 84 63]
 [42 85 49 54 80]
 [58 88 90 87 54]
 [59 42 38 88 84]
 [71 61 95 73 72]
 [46 61 95 57 78]
 [91 55 38 56 92]
 [80 64 84 75 60]
 [72 62 71 90 67]
 [79 98 69 46 96]
 [78 95 99 95 61]
 [57 82 91 94 58]
 [79 53 85 79 59]
 [40 38 62 67 93]
 [50 69 77 61 66]
 [67 98 82 70 87]
 [96 83 90 52 56]
 [64 51 38 73 95]
 [89 78 53 70 62]
 [62 64 98 54 89]
 [70 80 76 70 91]
 [69 40 42 78 58]
 [81 71 59 95 99]
 [74 58 66 85 76]
 [46 80 92 51 51]
 [99 87 40 48 54]
 [55 94 49 97 78]
 [65 97 63 94 86]
 [87 66 53 89 87]
 [96 67 88 55 68]
 [91 52 74 73 57]
 [99 59 59 80 97]
 [88 88 94 69 94]
 [41 92 66 65 50]
 [40 80 51 80 71]
 [87 58 65 54 66]
 [51 66 42 81 56]
 [44 81 84 53 74]
 [76 57 86 68 94]
 [71 61 67 79 53]
 [98 36 83 93 85]
 [94 51 99 79 55]
 [48 67 89 92 80]
 [80 43 42 80 68]
 [74 77 49 62 93]
 [58 82 53 93 88]
 [87 73 63 83 76]
 [55 76 63 76 59]
 [42 60 85 68 75]
 [59 84 58 67 68]
 [63 59 76 76 88]
 [93 58 73 81 52]
 [95 47 70 56 94]
 [72 94 99 93 62]
 [63 41 67 99 99]
 [91 91 74

### Represent each student’s scores as a vector

In [23]:
v1 = data[0]
print(v1)

[65 72 46 84 63]


### Compute Norm-1 and Norm-2

In [24]:
l1_norm = np.linalg.norm(v1, ord=1)
print("L1 Norm:", l1_norm)
l2_norm = np.linalg.norm(v1, ord=2)
print("L2 Norm:", l2_norm)

L1 Norm: 330.0
L2 Norm: 150.16657417681208


### Dot Product

In [25]:
v2 = data[1]

dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)

Dot Product: 20680


### Cross Product

In [26]:
v1_3d = v1[:3]
v2_3d = v2[:3]

cross_product = np.cross(v1_3d, v2_3d)
print("Cross Product:", cross_product)

Cross Product: [ -382 -1253  2501]


### Projection of One Vector onto Another

In [27]:
projection = (np.dot(v1, v2) / np.dot(v2, v2)) * v2
print("Projection of v1 on v2:", projection)

Projection of v1 on v2: [41.94726166 84.89326765 48.93847194 53.93219357 79.89954603]


## PART B: Matrix Operations

In [28]:
A = data
print("Matrix Shape:", A.shape)

Matrix Shape: (100, 5)


### Matrix Addition

In [29]:
B = A.copy()
addition = A + B
print("Matrix Addition (A + B):")
print(addition[:5])

Matrix Addition (A + B):
[[130 144  92 168 126]
 [ 84 170  98 108 160]
 [116 176 180 174 108]
 [118  84  76 176 168]
 [142 122 190 146 144]]


### Matrix Multiplication

In [30]:
multiplication = np.dot(A, A.T)
print("Matrix Multiplication (A x A^T) Shape:", multiplication.shape)

Matrix Multiplication (A x A^T) Shape: (100, 100)


### Transpose

In [31]:
transpose = A.T
print("Transpose Shape:", transpose.shape)

Transpose Shape: (5, 100)


### Determinant

In [32]:
square_matrix = A[:5, :5]

det = np.linalg.det(square_matrix)
print("Determinant:", det)

Determinant: 240275372.0000003


### Inverse

In [33]:
if det != 0:
    inverse = np.linalg.inv(square_matrix)
    print("Inverse Matrix:")
    print(inverse)
else:
    print("Matrix is singular, inverse not possible")

Inverse Matrix:
[[ 0.05092227 -0.00994234 -0.03768078 -0.02793651  0.02734324]
 [ 0.01411738  0.01137841  0.00211621 -0.0154866  -0.00851483]
 [-0.02281207 -0.00178566  0.01251414  0.0025061   0.00963525]
 [-0.01273221 -0.01240404  0.02650958  0.0229463  -0.02172991]
 [-0.01916727  0.01509662 -0.00802493  0.01409745  0.00345791]]


### PART C – Linear Transformations 

### Scaling Transformation

In [34]:
X = df[subjects].values
A = 1.1 * np.identity(5)
X_scaled = X @ A

print(X_scaled[:5])

[[ 71.5  79.2  50.6  92.4  69.3]
 [ 46.2  93.5  53.9  59.4  88. ]
 [ 63.8  96.8  99.   95.7  59.4]
 [ 64.9  46.2  41.8  96.8  92.4]
 [ 78.1  67.1 104.5  80.3  79.2]]


### Rotation Transformation

In [35]:
theta = np.radians(30)

R = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])

X_2D = X[:, :2]  # Math & Physics
X_rotated = X_2D @ R

print(X_rotated[:5])

[[92.29165125 29.85382907]
 [78.87306696 52.61215932]
 [94.22947342 47.21023553]
 [72.09549882  6.87306696]
 [91.98780367 17.32754963]]


### PART D – Eigenvalues + SVD

### Covariance Matrix

In [36]:
X_standardized = StandardScaler().fit_transform(X)
cov_matrix = np.cov(X_standardized.T)

print(cov_matrix)

[[ 1.01010101 -0.10615899  0.06458079 -0.11549864  0.04099121]
 [-0.10615899  1.01010101 -0.02533667 -0.10357742  0.07998609]
 [ 0.06458079 -0.02533667  1.01010101 -0.0750317  -0.16455373]
 [-0.11549864 -0.10357742 -0.0750317   1.01010101 -0.14345775]
 [ 0.04099121  0.07998609 -0.16455373 -0.14345775  1.01010101]]


### Eigenvalues & Eigenvectors

In [37]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Eigenvalues:
 [0.80346119 0.74943571 1.05949726 1.1828438  1.25526708]

Eigenvectors:
 [[-0.62667672  0.07411015 -0.4215685  -0.64533058  0.08724913]
 [-0.58196457  0.12347665  0.64330357  0.2172364   0.43016231]
 [ 0.24178254  0.53880122  0.50696979 -0.54601012 -0.3099823 ]
 [-0.34327479  0.56938128 -0.23704102  0.48361107 -0.51758986]
 [ 0.30380445  0.60395314 -0.30859958  0.06595504  0.6658526 ]]


### Singular Value Decomposition

In [38]:
U, S, VT = np.linalg.svd(X_standardized)

print("Singular Values:\n", S)

Singular Values:
 [11.14771014 10.82134633 10.2415931   8.91866907  8.61360175]


### PART E – PCA + LDA

### PCA

In [39]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_standardized)

print("Explained Variance Ratio:", pca.explained_variance_ratio_)

Explained Variance Ratio: [0.24854288 0.23420307]


### LDA

In [40]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

y = df["Performance_Category"]

lda = LinearDiscriminantAnalysis(n_components=1)
X_lda = lda.fit_transform(X_standardized, y)

print(X_lda[:5])

[[ 1.56593053]
 [ 2.84926199]
 [-0.9476069 ]
 [ 2.14520559]
 [-0.98067452]]
